INSERT INTO providers (
    NPI, entity_type_code, replacement_npi, employer_identification_number,
    provider_organization_name, provider_last_name, provider_first_name, provider_middle_name,
    provider_name_prefix_text, provider_name_suffix_text, provider_credential_text,
    provider_other_organization_name, provider_other_organization_name_type_code,
    provider_other_last_name, provider_other_first_name, provider_other_middle_name,
    provider_other_name_prefix_text, provider_other_name_suffix_text, provider_other_credential_text,
    provider_other_last_name_type_code, provider_enumeration_date, last_update_date,
    npi_deactivation_reason_code, npi_deactivation_date, npi_reactivation_date,
    provider_sex_code, is_sole_proprietor, is_organization_subpart, parent_organization_lbn,
    parent_organization_tin, certification_date
)
SELECT
    "NPI",
    COALESCE("Entity_Type_Code", 'N/A'),
    CASE WHEN "Replacement_NPI" IN ('', 'N/A') THEN 0 ELSE "Replacement_NPI"::BIGINT END,
    COALESCE("Employer_Identification_Number_EIN", 'N/A'),
    COALESCE("Provider_Organization_Name_Legal_Business_Name", 'N/A'),
    COALESCE("Provider_Last_Name_Legal_Name", 'N/A'),
    COALESCE("Provider_First_Name", 'N/A'),
    COALESCE("Provider_Middle_Name", 'N/A'),
    COALESCE("Provider_Name_Prefix_Text", 'N/A'),
    COALESCE("Provider_Name_Suffix_Text", 'N/A'),
    COALESCE("Provider_Credential_Text", 'N/A'),
    COALESCE("Provider_Other_Organization_Name", 'N/A'),
    COALESCE("Provider_Other_Organization_Name_Type_Code", 'N/A'),
    COALESCE("Provider_Other_Last_Name", 'N/A'),
    COALESCE("Provider_Other_First_Name", 'N/A'),
    COALESCE("Provider_Other_Middle_Name", 'N/A'),
    COALESCE("Provider_Other_Name_Prefix_Text", 'N/A'),
    COALESCE("Provider_Other_Name_Suffix_Text", 'N/A'),
    COALESCE("Provider_Other_Credential_Text", 'N/A'),
    COALESCE("Provider_Other_Last_Name_Type_Code", 'N/A'),
    CASE WHEN "Provider_Enumeration_Date" IN ('', 'N/A') THEN '1900-01-01'::DATE ELSE TO_DATE("Provider_Enumeration_Date", 'MM/DD/YYYY') END,
    CASE WHEN "Last_Update_Date" IN ('', 'N/A') THEN '1900-01-01'::DATE ELSE TO_DATE("Last_Update_Date", 'MM/DD/YYYY') END,
    COALESCE("NPI_Deactivation_Reason_Code", 'N/A'),
    CASE WHEN "NPI_Deactivation_Date" IN ('', 'N/A') THEN '1900-01-01'::DATE ELSE TO_DATE("NPI_Deactivation_Date", 'MM/DD/YYYY') END,
    CASE WHEN "NPI_Reactivation_Date" IN ('', 'N/A') THEN '1900-01-01'::DATE ELSE TO_DATE("NPI_Reactivation_Date", 'MM/DD/YYYY') END,
    COALESCE(CASE WHEN "Provider_Sex_Code" IN ('', 'N/A') THEN '' ELSE LEFT("Provider_Sex_Code", 1) END, ''),
    CASE WHEN TRIM("Is_Sole_Proprietor") IN ('', 'N/A', 'X', ' ') THEN 'X'::YES_OR_NO ELSE "Is_Sole_Proprietor"::YES_OR_NO END,
    CASE WHEN TRIM("Is_Organization_Subpart") IN ('', 'N/A', 'X', ' ') THEN 'X'::YES_OR_NO ELSE "Is_Organization_Subpart"::YES_OR_NO END,
    COALESCE("Parent_Organization_LBN", 'N/A'),
    COALESCE("Parent_Organization_TIN", 'N/A'),
    CASE WHEN "Certification_Date" IN ('', 'N/A') THEN '1900-01-01'::DATE ELSE TO_DATE("Certification_Date", 'MM/DD/YYYY') END
FROM STAGING_TABLE_NPI s;