CREATE TABLE IF NOT EXISTS STAGING_TABLE(
    NPI VARCHAR(10) NOT NULL,
    ENDPOINT_TYPE VARCHAR(50) NOT NULL,
    ENDPOINT_TYPE_DESCRIPTION VARCHAR(50),
    ENDPOINT VARCHAR(1000),
    AFFILIATION YES_OR_NO,
    ENDPOINT_DESCRIPTION VARCHAR(1000),
    BUSINESS_NAME VARCHAR(100),
    USE_CODE VARCHAR(25),
    USE_DESCRIPTION VARCHAR(100),
    OTHER_USE_DESCRIPTION VARCHAR(200),
    CONTENT_TYPE VARCHAR(25),
    CONTENT_DESCRIPTION VARCHAR(100),
    OTHER_CONTENT_DESCRIPTION VARCHAR(200),
    AFFILIATION_PRIMARY_ADDRESS VARCHAR(55),
    AFFILIATION_SECONDARY_ADDRESS VARCHAR(55),
    AFFILIATION_ADDRESS_CITY VARCHAR(40),
    AFFILIATION_ADDRESS_STATE VARCHAR(40),
    AFFILIATION_ADDRESS_COUNTRY CHAR(2),
    AFFILIATION_ADDRESS_POSTAL_CODE VARCHAR
);

DELETE FROM staging_table
WHERE LENGTH(affiliation_address_postal_code) >= 10;

INSERT INTO ENDPOINT_AFFILIATION(
	AFFILIATION_PRIMARY_ADDRESS, 
	AFFILIATION_SECONDARY_ADDRESS, 
	AFFILIATION_ADDRESS_CITY,
	AFFILIATION_ADDRESS_STATE, 
	AFFILIATION_ADDRESS_COUNTRY,
	AFFILIATION_ADDRESS_POSTAL_CODE)
SELECT DISTINCT
    COALESCE(AFFILIATION_PRIMARY_ADDRESS, 'N/A'), 
    COALESCE(AFFILIATION_SECONDARY_ADDRESS, 'No Secondary Address'),
    COALESCE(AFFILIATION_ADDRESS_CITY, 'N/A'),
    COALESCE(AFFILIATION_ADDRESS_STATE, 'N/A'),
    COALESCE(AFFILIATION_ADDRESS_COUNTRY, 'XX'),
    COALESCE(AFFILIATION_ADDRESS_POSTAL_CODE, 'N/A')
FROM STAGING_TABLE;

INSERT INTO ENDPOINTS(
    NPI,
    ENDPOINT_TYPE,
    ENDPOINT_TYPE_DESCRIPTION,
    ENDPOINT,
    AFFILIATION,
    AFFILIATION_ID,
    ENDPOINT_DESCRIPTION,
    BUSINESS_NAME,
    USE_CODE,
    USE_DESCRIPTION,
    OTHER_USE_DESCRIPTION,
    CONTENT_TYPE,
    CONTENT_DESCRIPTION,
    OTHER_CONTENT_DESCRIPTION
)
SELECT
    st.NPI,
    st.ENDPOINT_TYPE,
    COALESCE(st.ENDPOINT_TYPE_DESCRIPTION, 'N/A'),
    COALESCE(st.ENDPOINT, 'N/A'),
    COALESCE(st.AFFILIATION, 'X'),
    e.AFFILIATION_ID,
    COALESCE(st.ENDPOINT_DESCRIPTION, 'N/A'),
    COALESCE(st.BUSINESS_NAME, 'N/A'),
    COALESCE(st.USE_CODE, 'N/A'),
    COALESCE(st.USE_DESCRIPTION, 'N/A'),
    COALESCE(st.OTHER_CONTENT_DESCRIPTION, 'N/A'),
    COALESCE(st.CONTENT_TYPE, 'N/A'),
    COALESCE(st.CONTENT_DESCRIPTION, 'N/A'),
    COALESCE(st.OTHER_CONTENT_DESCRIPTION, 'N/A')
FROM STAGING_TABLE st
JOIN ENDPOINT_AFFILIATION e ON 
COALESCE(st.AFFILIATION_PRIMARY_ADDRESS, 'N/A') = e.AFFILIATION_PRIMARY_ADDRESS AND 
COALESCE(st.AFFILIATION_SECONDARY_ADDRESS, 'No Secondary Address') = e.AFFILIATION_SECONDARY_ADDRESS AND
COALESCE(st.AFFILIATION_ADDRESS_CITY, 'N/A') = e.AFFILIATION_ADDRESS_CITY AND
COALESCE(st.AFFILIATION_ADDRESS_STATE, 'N/A') = e.AFFILIATION_ADDRESS_STATE AND
COALESCE(st.AFFILIATION_ADDRESS_COUNTRY, 'XX') = e.AFFILIATION_ADDRESS_COUNTRY AND
COALESCE(st.AFFILIATION_ADDRESS_POSTAL_CODE, 'N/A') = e.AFFILIATION_ADDRESS_POSTAL_CODE;

DELETE TABLE STAGING_TABLE;