CREATE TABLE IF NOT EXISTS STAGING_TABLE(
    NPI VARCHAR(10) NOT NULL,
    ENDPOINT_TYPE VARCHAR(50) NOT NULL,
    ENDPOINT_TYPE_DESCRIPTION VARCHAR(50) DEFAULT 'N/A',
    ENDPOINT VARCHAR(1000) DEFAULT 'N/A',
    AFFILIATION YES_OR_NO DEFAULT 'X',
    ENDPOINT_DESCRIPTION VARCHAR(1000) DEFAULT 'N/A',
    BUSINESS_NAME VARCHAR(100) DEFAULT 'N/A',
    USE_CODE VARCHAR(25) DEFAULT 'N/A',
    USE_DESCRIPTION VARCHAR(100) DEFAULT 'N/A',
    OTHER_USE_DESCRIPTION VARCHAR(200) DEFAULT 'N/A',
    CONTENT_TYPE VARCHAR(25) DEFAULT 'N/A',
    CONTENT_DESCRIPTION VARCHAR(100) DEFAULT 'N/A',
    OTHER_CONTENT_DESCRIPTION VARCHAR(200) DEFAULT 'N/A',
    AFFILIATION_PRIMARY_ADDRESS VARCHAR(55) DEFAULT 'N/A',
    AFFILIATION_SECONDARY_ADDRESS VARCHAR(55) DEFAULT 'N/A',
    AFFILIATION_ADDRESS_CITY VARCHAR(40) DEFAULT 'N/A',
    AFFILIATION_ADDRESS_STATE VARCHAR(40) DEFAULT 'N/A',
    AFFILIATION_ADDRESS_COUNTRY CHAR(2) DEFAULT 'XX',
    AFFILIATION_ADDRESS_POSTAL_CODE VARCHAR DEFAULT '000000000'
);

DELETE FROM staging_table
WHERE LENGTH(affiliation_address_postal_code) >= 10;

INSERT INTO ENDPOINT_AFFILIATION(
	AFFILIATION_PRIMARY_ADDRESS, 
	AFFILIATION_SECONDARY_ADDRESS, 
	AFFILIATION_ADDRESS_CITY,
	AFFILIATION_ADDRESS_STATE, 
	AFFILIATION_ADDRESS_COUNTRY,
	AFFILIATION_ADDRESS_POSTAL_CODE)
SELECT DISTINCT
    COALESCE(AFFILIATION_PRIMARY_ADDRESS, 'N/A'), 
    COALESCE(AFFILIATION_SECONDARY_ADDRESS, 'No Value'),
    COALESCE(AFFILIATION_ADDRESS_CITY, 'N/A'),
    COALESCE(AFFILIATION_ADDRESS_STATE, 'N/A'),
    COALESCE(AFFILIATION_ADDRESS_COUNTRY, 'XX'),
    COALESCE(AFFILIATION_ADDRESS_POSTAL_CODE, 'N/A')
FROM STAGING_TABLE;

INSERT INTO ENDPOINTS(
    NPI,
    ENDPOINT_TYPE,
    ENDPOINT_TYPE_DESCRIPTION,
    ENDPOINT,
    AFFILIATION,
    AFFILIATION_ID,
    ENDPOINT_DESCRIPTION,
    BUSINESS_NAME,
    USE_CODE,
    USE_DESCRIPTION,
    OTHER_USE_DESCRIPTION,
    CONTENT_TYPE,
    CONTENT_DESCRIPTION,
    OTHER_CONTENT_DESCRIPTION
)
SELECT
    st.NPI,
    st.ENDPOINT_TYPE,
    st.ENDPOINT_TYPE_DESCRIPTION,
    st.ENDPOINT,
    st.AFFILIATION,
    e.AFFILIATION_ID,
    st.ENDPOINT_DESCRIPTION,
    st.BUSINESS_NAME,
    st.USE_CODE,
    st.USE_DESCRIPTION,
    st.OTHER_CONTENT_DESCRIPTION,
    st.CONTENT_TYPE,
    st.CONTENT_DESCRIPTION,
    st.OTHER_CONTENT_DESCRIPTION
FROM STAGING_TABLE st
JOIN ENDPOINT_AFFILIATION e ON 
st.AFFILIATION_PRIMARY_ADDRESS = e.AFFILIATION_PRIMARY_ADDRESS AND 
st.AFFILIATION_SECONDARY_ADDRESS = e.AFFILIATION_SECONDARY_ADDRESS AND
st.AFFILIATION_ADDRESS_CITY = e.AFFILIATION_ADDRESS_CITY AND
st.AFFILIATION_ADDRESS_STATE = e.AFFILIATION_ADDRESS_STATE AND
st.AFFILIATION_ADDRESS_COUNTRY = e.AFFILIATION_ADDRESS_COUNTRY AND
st.AFFILIATION_ADDRESS_POSTAL_CODE = e.AFFILIATION_ADDRESS_POSTAL_CODE;

DELETE TABLE STAGING_TABLE;