CREATE TYPE YES_OR_NO AS ENUM ('Y','N','X');

CREATE TABLE IF NOT EXISTS ENDPOINT_AFFILIATION(
    AFFILIATION_ID SERIAL PRIMARY KEY,
    AFFILIATION_PRIMARY_ADDRESS VARCHAR(55) NOT NULL DEFAULT 'N/A',
    AFFILIATION_SECONDARY_ADDRESS VARCHAR(55) NOT NULL DEFAULT 'N/A',
    AFFILIATION_ADDRESS_CITY VARCHAR(40) NOT NULL DEFAULT 'N/A',
    AFFILIATION_ADDRESS_STATE VARCHAR(40) NOT NULL DEFAULT 'N/A',
    AFFILIATION_ADDRESS_COUNTRY CHAR(2) NOT NULL DEFAULT 'XX',
    AFFILIATION_ADDRESS_POSTAL_CODE VARCHAR(9) NOT NULL DEFAULT '000000000'
);

CREATE TABLE IF NOT EXISTS ENDPOINTS(
    NPI VARCHAR(10) NOT NULL,
    ENDPOINT_TYPE VARCHAR(50) NOT NULL,
    ENDPOINT_TYPE_DESCRIPTION VARCHAR(50) NOT NULL DEFAULT 'N/A',
    ENDPOINT VARCHAR(1000) NOT NULL DEFAULT 'N/A',
    AFFILIATION YES_OR_NO NOT NULL DEFAULT 'X',
    AFFILIATION_ID INT NOT NULL,
    ENDPOINT_DESCRIPTION VARCHAR(1000) NOT NULL DEFAULT 'N/A',
    BUSINESS_NAME VARCHAR(100) NOT NULL DEFAULT 'N/A',
    USE_CODE VARCHAR(25) NOT NULL DEFAULT 'N/A',
    USE_DESCRIPTION VARCHAR(100) NOT NULL DEFAULT 'N/A',
    OTHER_USE_DESCRIPTION VARCHAR(200) NOT NULL DEFAULT 'N/A',
    CONTENT_TYPE VARCHAR(25) NOT NULL DEFAULT 'N/A',
    CONTENT_DESCRIPTION VARCHAR(100) NOT NULL DEFAULT 'N/A',
    OTHER_CONTENT_DESCRIPTION VARCHAR(200) NOT NULL DEFAULT 'N/A',
    FOREIGN KEY (AFFILIATION_ID) REFERENCES ENDPOINT_AFFILIATION(AFFILIATION_ID)
);

