INSERT INTO ENDPOINT_AFFILIATION(
	AFFILIATION_PRIMARY_ADDRESS, 
	AFFILIATION_SECONDARY_ADDRESS, 
	AFFILIATION_ADDRESS_CITY,
	AFFILIATION_ADDRESS_STATE, 
	AFFILIATION_ADDRESS_COUNTRY,
	AFFILIATION_ADDRESS_POSTAL_CODE)
SELECT DISTINCT
    COALESCE(AFFILIATION_PRIMARY_ADDRESS, 'N/A'), 
    COALESCE(AFFILIATION_SECONDARY_ADDRESS, 'No Secondary Address'),
    COALESCE(AFFILIATION_ADDRESS_CITY, 'N/A'),
    COALESCE(AFFILIATION_ADDRESS_STATE, 'N/A'),
    COALESCE(AFFILIATION_ADDRESS_COUNTRY, 'XX'),
    COALESCE(AFFILIATION_ADDRESS_POSTAL_CODE, 'N/A')
FROM STAGING_TABLE_ENDPOINTS;

INSERT INTO ENDPOINTS(
    NPI,
    ENDPOINT_TYPE,
    ENDPOINT_TYPE_DESCRIPTION,
    ENDPOINT,
    AFFILIATION,
    AFFILIATION_ID,
    ENDPOINT_DESCRIPTION,
    BUSINESS_NAME,
    USE_CODE,
    USE_DESCRIPTION,
    OTHER_USE_DESCRIPTION,
    CONTENT_TYPE,
    CONTENT_DESCRIPTION,
    OTHER_CONTENT_DESCRIPTION
)
SELECT
    st.NPI,
    st.ENDPOINT_TYPE,
    COALESCE(st.ENDPOINT_TYPE_DESCRIPTION, 'N/A'),
    COALESCE(st.ENDPOINT, 'N/A'),
    COALESCE(st.AFFILIATION, 'X'),
    e.AFFILIATION_ID,
    COALESCE(st.ENDPOINT_DESCRIPTION, 'N/A'),
    COALESCE(st.BUSINESS_NAME, 'N/A'),
    COALESCE(st.USE_CODE, 'N/A'),
    COALESCE(st.USE_DESCRIPTION, 'N/A'),
    COALESCE(st.OTHER_CONTENT_DESCRIPTION, 'N/A'),
    COALESCE(st.CONTENT_TYPE, 'N/A'),
    COALESCE(st.CONTENT_DESCRIPTION, 'N/A'),
    COALESCE(st.OTHER_CONTENT_DESCRIPTION, 'N/A')
FROM STAGING_TABLE_ENDPOINTS st
JOIN ENDPOINT_AFFILIATION e ON 
COALESCE(st.AFFILIATION_PRIMARY_ADDRESS, 'N/A') = e.AFFILIATION_PRIMARY_ADDRESS AND 
COALESCE(st.AFFILIATION_SECONDARY_ADDRESS, 'No Secondary Address') = e.AFFILIATION_SECONDARY_ADDRESS AND
COALESCE(st.AFFILIATION_ADDRESS_CITY, 'N/A') = e.AFFILIATION_ADDRESS_CITY AND
COALESCE(st.AFFILIATION_ADDRESS_STATE, 'N/A') = e.AFFILIATION_ADDRESS_STATE AND
COALESCE(st.AFFILIATION_ADDRESS_COUNTRY, 'XX') = e.AFFILIATION_ADDRESS_COUNTRY AND
COALESCE(st.AFFILIATION_ADDRESS_POSTAL_CODE, 'N/A') = e.AFFILIATION_ADDRESS_POSTAL_CODE;

INSERT INTO provider_othername (npi, other_name, name_type_code)
SELECT
    npi,
    provider_other_organization_name,
    provider_other_organization_name_type_code
FROM staging_othername_pfile
WHERE
    npi IS NOT NULL AND npi <> ''
    AND provider_other_organization_name IS NOT NULL AND provider_other_organization_name <> ''
    AND provider_other_organization_name_type_code IN ('3', '4', '5','6');

--# Drop all staging tables once finished.
DROP TABLE STAGING_TABLE_ENDPOINTS;
DROP TABLE STAGING_TABLE_NPI;
DROP TABLE STAGING_OTHERNAME_PFILE;
